### ISSUE TITLE
Doesn't work in user mode on Linux Mint 19.3

### ISSUE THREAD

**Issue by Brain0verride** [timothycrosley/streamdeck-ui#43]
Working fine in root but in user (after fixing group, udev, etc.) I have this error message : 

Traceback (most recent call last):
  File "/home/brain0verride/.local/bin/streamdeck", line 11, in <module>
    sys.exit(start())
  File "/home/brain0verride/.local/lib/python3.6/site-packages/streamdeck_ui/gui.py", line 269, in start
    build_device(ui)
  File "/home/brain0verride/.local/lib/python3.6/site-packages/streamdeck_ui/gui.py", line 201, in build_device
    sync(ui)
  File "/home/brain0verride/.local/lib/python3.6/site-packages/streamdeck_ui/gui.py", line 190, in sync
    api.ensure_decks_connected()
  File "/home/brain0verride/.local/lib/python3.6/site-packages/streamdeck_ui/api.py", line 115, in ensure_decks_connected
    if not deck.connected():
  File "/home/brain0verride/.local/lib/python3.6/site-packages/StreamDeck/Devices/StreamDeck.py", line 148, in connected
    return self.device.connected()
  File "/home/brain0verride/.local/lib/python3.6/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 321, in connected
    return any([d['path'] == self.hid_info['path'] for d in self.hidapi.enumerate()])
  File "/home/brain0verride/.local/lib/python3.6/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 147, in enumerate
    'path': current_device.path,
AttributeError: 'LP_hid_device_info' object has no attribute 'path'
Erreur de segmentation (core dumped)

I've also try with sudo and with a chmod +x without success.

**Comment by Brain0verride** [comment]
strace log
[streamdeck.log](https://github.com/timothycrosley/streamdeck-ui/files/4482398/streamdeck.log)

**Comment by abcminiuser** [comment]
Sorry, that was my screw up, It's patched in `streamdeck` version 0.7.3.

**Comment by T-Grave** [comment]
I'm having the same issue on PopOS 19.04.

How do we use the newest streamdeck version @abcminiuser ?

I did a fresh install today and it installs 0.6.3 by default

**Comment by itsUnsmart** [comment]
I have similar issue on elementary os

```
QApplication: invalid style override 'adwaita' passed, ignoring it.
	Available styles: Windows, Fusion
Traceback (most recent call last):
  File "/home/garret/.local/bin/streamdeck", line 8, in <module>
    sys.exit(start())
  File "/home/garret/.local/lib/python3.6/site-packages/streamdeck_ui/gui.py", line 266, in start
    for deck_id, deck in api.open_decks().items():
  File "/home/garret/.local/lib/python3.6/site-packages/streamdeck_ui/api.py", line 100, in open_decks
    deck.open()
  File "/home/garret/.local/lib/python3.6/site-packages/StreamDeck/Devices/StreamDeck.py", line 122, in open
    self.device.open()
  File "/home/garret/.local/lib/python3.6/site-packages/StreamDeck/Transport/HIDAPI.py", line 48, in open
    self.hid.open_path(self.hid_info['path'])
  File "hid.pyx", line 72, in hid.device.open_path
OSError: open failed
```

Any fix for this?

**Comment by abcminiuser** [comment]
Update to `streamdeck-0.8.0`.

**Comment by jms1989** [comment]
`streamdeck-0.8.0` isn't compatible with the UI. I can't install anything newer than 0.6.3.

```
$pip3 install --user streamdeck==0.8.0
Collecting streamdeck==0.8.0
  Using cached streamdeck-0.8.0-py3-none-any.whl (24 kB)
ERROR: streamdeck-ui 1.0.2 has requirement streamdeck<0.7.0,>=0.6.3, but you'll have streamdeck 0.8.0 which is incompatible.
Installing collected packages: streamdeck
  Attempting uninstall: streamdeck
    Found existing installation: streamdeck 0.6.3
    Uninstalling streamdeck-0.6.3:
      Successfully uninstalled streamdeck-0.6.3
Successfully installed streamdeck-0.8.0
```
Please update the UI's requirements.

**Comment by hutber** [comment]
Ok, so for me, it turns out that despite me thinking "No, that USB port 100% works... it turns out changing the USB port was the key to getting this working... shocked and stunned :D

**Comment by hutber** [comment]
I had the exact same error otherwise.

**Comment by dodgyrabbit** [comment]
Please try the latest master, which uses the an updated streamdeck library and other dependencies also updated.
There are several issues mentioned here - it's not clear anymore which one we're trying to solve!

If you can still reproduce, please reopen and provide relevant steps to reproduce, which operating system etc. 
Thank you!
