### ISSUE TITLE
cant load after installing (used ubuntu script)

### ISSUE THREAD

**Issue by alexdavisau** [timothycrosley/streamdeck-ui#41]
hi - i am trying to get my XL working in ubuntu19.10
i ran the ubuntu script and when completed i tried to load but got the following error

Traceback (most recent call last):
  File "/home/alex/.local/bin/streamdeck", line 10, in <module>
    sys.exit(start())
  File "/home/alex/.local/lib/python3.7/site-packages/streamdeck_ui/gui.py", line 266, in start
    for deck_id, deck in api.open_decks().items():
  File "/home/alex/.local/lib/python3.7/site-packages/streamdeck_ui/api.py", line 99, in open_decks
    for deck in DeviceManager.DeviceManager().enumerate():
  File "/home/alex/.local/lib/python3.7/site-packages/StreamDeck/DeviceManager.py", line 90, in __init__
    self.transport = self._get_transport(transport)
  File "/home/alex/.local/lib/python3.7/site-packages/StreamDeck/DeviceManager.py", line 82, in _get_transport
    raise ProbeError("Probe failed to find any functional HID backend.", probe_errors)
StreamDeck.DeviceManager.ProbeError: ('Probe failed to find any functional HID backend.', {'hid': OSError('The libhidapi-hidraw0 backend is currently blacklisted for StreamDeck devices.'), 'hidapi': TypeError("enumerate() got an unexpected keyword argument 'vendor_id'")})

**Comment by abcminiuser** [comment]
Try upgrading your Python `streamdeck` package to 0.7.3, which should fix this.

**Comment by Brain0verride** [comment]
Thanks for your job, now the app seems to run correctly.

**Comment by Brain0verride** [comment]
I have another problem, I try to use it to automate ssh connections, but it seems I can only launch command from the same term I've launched streamdeck. Do you have an idea ?

**Comment by Licenser** [comment]
I'm having the same issue, updating to streamdeck 0.7.3 doesn't seem to fix it, the streamdeck_ui also requires "^0.6.3" after changing that too, and installing 2 more packages `libhidapi-libusb0` and `python3-hidapi` that were missing I'm arriving at a new error:

```
  File "/home/heinz/.local/bin/streamdeck", line 8, in <module>
    sys.exit(start())
  File "/home/heinz/.local/lib/python3.8/site-packages/streamdeck_ui/gui.py", line 266, in start
    for deck_id, deck in api.open_decks().items():
  File "/home/heinz/.local/lib/python3.8/site-packages/streamdeck_ui/api.py", line 100, in open_decks
    deck.open()
  File "/home/heinz/.local/lib/python3.8/site-packages/StreamDeck/Devices/StreamDeck.py", line 127, in open
    self.device.open()
  File "/home/heinz/.local/lib/python3.8/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 301, in open
    self.device_handle = self.hidapi.open_device(self.device_info['path'])
  File "/home/heinz/.local/lib/python3.8/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 168, in open_device
    raise TransportError("Could not open HID device.")
StreamDeck.Transport.Transport.TransportError: Could not open HID device.
```

**Comment by Licenser** [comment]
a reboot fixed that

**Comment by hutber** [comment]
Interesting. I am having the same issue from a fresh install on Mint 20.3. Still miffed on how to fix it.

**Comment by hutber** [comment]
Seems the issue was simple for me I missed this from the install guide:
```
Add the udev rules using your text editor:

sudoedit /etc/udev/rules.d/70-streamdeck.rules
# If that doesn't work, try:
sudo nano /etc/udev/rules.d/70-streamdeck.rules
```
